spring:
  profiles:
    default: local

  messages:
    basename: messages, errors
    encoding: UTF-8

---
spring:
  config:
    activate:
      on-profile: local

#  datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:~/beapi
#    username: sa
#    password:
